# FROM eclipse-temurin:21-jdk-jammy AS build
# WORKDIR /app
# COPY . .
# RUN ./gradlew clean build -x test

# FROM eclipse-temurin:21-jre-jammy
# WORKDIR /app
# COPY --from=build /app/build/libs/*.jar app.jar
# EXPOSE 8080
# ENTRYPOINT ["java", "-jar", "app.jar"]

FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/app.jar"]
